// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: card/v1alpha1/card_api.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DealRequest define request schema of Deal API
type DealRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DealRequest) Reset() {
	*x = DealRequest{}
	mi := &file_card_v1alpha1_card_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DealRequest) ProtoMessage() {}

func (x *DealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_card_v1alpha1_card_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DealRequest.ProtoReflect.Descriptor instead.
func (*DealRequest) Descriptor() ([]byte, []int) {
	return file_card_v1alpha1_card_api_proto_rawDescGZIP(), []int{0}
}

// DealResponse define response schema of Deal API
type DealResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// card entity of card
	Card          *Card `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DealResponse) Reset() {
	*x = DealResponse{}
	mi := &file_card_v1alpha1_card_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DealResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DealResponse) ProtoMessage() {}

func (x *DealResponse) ProtoReflect() protoreflect.Message {
	mi := &file_card_v1alpha1_card_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DealResponse.ProtoReflect.Descriptor instead.
func (*DealResponse) Descriptor() ([]byte, []int) {
	return file_card_v1alpha1_card_api_proto_rawDescGZIP(), []int{1}
}

func (x *DealResponse) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

// PingRequest define request schema of Ping API
type PingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// now is the timestamp when the request is sent
	Now           *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=now,proto3" json:"now,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_card_v1alpha1_card_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_card_v1alpha1_card_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_card_v1alpha1_card_api_proto_rawDescGZIP(), []int{2}
}

func (x *PingRequest) GetNow() *timestamppb.Timestamp {
	if x != nil {
		return x.Now
	}
	return nil
}

// PingResponse define response schema of Ping API
type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_card_v1alpha1_card_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_card_v1alpha1_card_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_card_v1alpha1_card_api_proto_rawDescGZIP(), []int{3}
}

var File_card_v1alpha1_card_api_proto protoreflect.FileDescriptor

const file_card_v1alpha1_card_api_proto_rawDesc = "" +
	"\n" +
	"\x1ccard/v1alpha1/card_api.proto\x12\rcard.v1alpha1\x1a\x18card/v1alpha1/card.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\r\n" +
	"\vDealRequest\"7\n" +
	"\fDealResponse\x12'\n" +
	"\x04card\x18\x01 \x01(\v2\x13.card.v1alpha1.CardR\x04card\";\n" +
	"\vPingRequest\x12,\n" +
	"\x03now\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x03now\"\x0e\n" +
	"\fPingResponse2\x8f\x01\n" +
	"\vCardService\x12?\n" +
	"\x04Deal\x12\x1a.card.v1alpha1.DealRequest\x1a\x1b.card.v1alpha1.DealResponse\x12?\n" +
	"\x04Ping\x12\x1a.card.v1alpha1.PingRequest\x1a\x1b.card.v1alpha1.PingResponseB.Z,github.com/openpoker-dev/gengo/card/v1alpha1b\x06proto3"

var (
	file_card_v1alpha1_card_api_proto_rawDescOnce sync.Once
	file_card_v1alpha1_card_api_proto_rawDescData []byte
)

func file_card_v1alpha1_card_api_proto_rawDescGZIP() []byte {
	file_card_v1alpha1_card_api_proto_rawDescOnce.Do(func() {
		file_card_v1alpha1_card_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_card_v1alpha1_card_api_proto_rawDesc), len(file_card_v1alpha1_card_api_proto_rawDesc)))
	})
	return file_card_v1alpha1_card_api_proto_rawDescData
}

var file_card_v1alpha1_card_api_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_card_v1alpha1_card_api_proto_goTypes = []any{
	(*DealRequest)(nil),           // 0: card.v1alpha1.DealRequest
	(*DealResponse)(nil),          // 1: card.v1alpha1.DealResponse
	(*PingRequest)(nil),           // 2: card.v1alpha1.PingRequest
	(*PingResponse)(nil),          // 3: card.v1alpha1.PingResponse
	(*Card)(nil),                  // 4: card.v1alpha1.Card
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_card_v1alpha1_card_api_proto_depIdxs = []int32{
	4, // 0: card.v1alpha1.DealResponse.card:type_name -> card.v1alpha1.Card
	5, // 1: card.v1alpha1.PingRequest.now:type_name -> google.protobuf.Timestamp
	0, // 2: card.v1alpha1.CardService.Deal:input_type -> card.v1alpha1.DealRequest
	2, // 3: card.v1alpha1.CardService.Ping:input_type -> card.v1alpha1.PingRequest
	1, // 4: card.v1alpha1.CardService.Deal:output_type -> card.v1alpha1.DealResponse
	3, // 5: card.v1alpha1.CardService.Ping:output_type -> card.v1alpha1.PingResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_card_v1alpha1_card_api_proto_init() }
func file_card_v1alpha1_card_api_proto_init() {
	if File_card_v1alpha1_card_api_proto != nil {
		return
	}
	file_card_v1alpha1_card_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_card_v1alpha1_card_api_proto_rawDesc), len(file_card_v1alpha1_card_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_card_v1alpha1_card_api_proto_goTypes,
		DependencyIndexes: file_card_v1alpha1_card_api_proto_depIdxs,
		MessageInfos:      file_card_v1alpha1_card_api_proto_msgTypes,
	}.Build()
	File_card_v1alpha1_card_api_proto = out.File
	file_card_v1alpha1_card_api_proto_goTypes = nil
	file_card_v1alpha1_card_api_proto_depIdxs = nil
}
