// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: card/v1alpha1/card_api.proto

package v1alpha1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1alpha1 "github.com/openpoker-dev/gengo/card/v1alpha1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// CardAPIName is the fully-qualified name of the CardAPI service.
	CardAPIName = "card.v1alpha1.CardAPI"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// CardAPIDealProcedure is the fully-qualified name of the CardAPI's Deal RPC.
	CardAPIDealProcedure = "/card.v1alpha1.CardAPI/Deal"
	// CardAPIPingProcedure is the fully-qualified name of the CardAPI's Ping RPC.
	CardAPIPingProcedure = "/card.v1alpha1.CardAPI/Ping"
)

// CardAPIClient is a client for the card.v1alpha1.CardAPI service.
type CardAPIClient interface {
	Deal(context.Context, *v1alpha1.DealRequest) (*v1alpha1.DealResponse, error)
	Ping(context.Context, *v1alpha1.PingRequest) (*v1alpha1.PingResponse, error)
}

// NewCardAPIClient constructs a client for the card.v1alpha1.CardAPI service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewCardAPIClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) CardAPIClient {
	baseURL = strings.TrimRight(baseURL, "/")
	cardAPIMethods := v1alpha1.File_card_v1alpha1_card_api_proto.Services().ByName("CardAPI").Methods()
	return &cardAPIClient{
		deal: connect.NewClient[v1alpha1.DealRequest, v1alpha1.DealResponse](
			httpClient,
			baseURL+CardAPIDealProcedure,
			connect.WithSchema(cardAPIMethods.ByName("Deal")),
			connect.WithClientOptions(opts...),
		),
		ping: connect.NewClient[v1alpha1.PingRequest, v1alpha1.PingResponse](
			httpClient,
			baseURL+CardAPIPingProcedure,
			connect.WithSchema(cardAPIMethods.ByName("Ping")),
			connect.WithClientOptions(opts...),
		),
	}
}

// cardAPIClient implements CardAPIClient.
type cardAPIClient struct {
	deal *connect.Client[v1alpha1.DealRequest, v1alpha1.DealResponse]
	ping *connect.Client[v1alpha1.PingRequest, v1alpha1.PingResponse]
}

// Deal calls card.v1alpha1.CardAPI.Deal.
func (c *cardAPIClient) Deal(ctx context.Context, req *v1alpha1.DealRequest) (*v1alpha1.DealResponse, error) {
	response, err := c.deal.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// Ping calls card.v1alpha1.CardAPI.Ping.
func (c *cardAPIClient) Ping(ctx context.Context, req *v1alpha1.PingRequest) (*v1alpha1.PingResponse, error) {
	response, err := c.ping.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// CardAPIHandler is an implementation of the card.v1alpha1.CardAPI service.
type CardAPIHandler interface {
	Deal(context.Context, *v1alpha1.DealRequest) (*v1alpha1.DealResponse, error)
	Ping(context.Context, *v1alpha1.PingRequest) (*v1alpha1.PingResponse, error)
}

// NewCardAPIHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewCardAPIHandler(svc CardAPIHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	cardAPIMethods := v1alpha1.File_card_v1alpha1_card_api_proto.Services().ByName("CardAPI").Methods()
	cardAPIDealHandler := connect.NewUnaryHandlerSimple(
		CardAPIDealProcedure,
		svc.Deal,
		connect.WithSchema(cardAPIMethods.ByName("Deal")),
		connect.WithHandlerOptions(opts...),
	)
	cardAPIPingHandler := connect.NewUnaryHandlerSimple(
		CardAPIPingProcedure,
		svc.Ping,
		connect.WithSchema(cardAPIMethods.ByName("Ping")),
		connect.WithHandlerOptions(opts...),
	)
	return "/card.v1alpha1.CardAPI/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case CardAPIDealProcedure:
			cardAPIDealHandler.ServeHTTP(w, r)
		case CardAPIPingProcedure:
			cardAPIPingHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedCardAPIHandler returns CodeUnimplemented from all methods.
type UnimplementedCardAPIHandler struct{}

func (UnimplementedCardAPIHandler) Deal(context.Context, *v1alpha1.DealRequest) (*v1alpha1.DealResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("card.v1alpha1.CardAPI.Deal is not implemented"))
}

func (UnimplementedCardAPIHandler) Ping(context.Context, *v1alpha1.PingRequest) (*v1alpha1.PingResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("card.v1alpha1.CardAPI.Ping is not implemented"))
}
