// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: game/v1alpha1/game.proto

package gamepb

import (
	v1alpha1 "github.com/openpoker-dev/gengo/card/v1alpha1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ActionType represents the type of action a player can take.
type ActionType int32

const (
	// ACTION_TYPE_UNSPECIFIED is the default unspecified action.
	ActionType_ACTION_TYPE_UNSPECIFIED ActionType = 0
	// ACTION_TYPE_FOLD represents folding the hand.
	ActionType_ACTION_TYPE_FOLD ActionType = 1
	// ACTION_TYPE_CHECK represents checking (passing action).
	ActionType_ACTION_TYPE_CHECK ActionType = 2
	// ACTION_TYPE_CALL represents calling the current bet.
	ActionType_ACTION_TYPE_CALL ActionType = 3
	// ACTION_TYPE_RAISE represents raising the current bet.
	ActionType_ACTION_TYPE_RAISE ActionType = 4
	// ACTION_TYPE_ALL_IN represents betting all remaining chips.
	ActionType_ACTION_TYPE_ALL_IN ActionType = 5
)

// Enum value maps for ActionType.
var (
	ActionType_name = map[int32]string{
		0: "ACTION_TYPE_UNSPECIFIED",
		1: "ACTION_TYPE_FOLD",
		2: "ACTION_TYPE_CHECK",
		3: "ACTION_TYPE_CALL",
		4: "ACTION_TYPE_RAISE",
		5: "ACTION_TYPE_ALL_IN",
	}
	ActionType_value = map[string]int32{
		"ACTION_TYPE_UNSPECIFIED": 0,
		"ACTION_TYPE_FOLD":        1,
		"ACTION_TYPE_CHECK":       2,
		"ACTION_TYPE_CALL":        3,
		"ACTION_TYPE_RAISE":       4,
		"ACTION_TYPE_ALL_IN":      5,
	}
)

func (x ActionType) Enum() *ActionType {
	p := new(ActionType)
	*p = x
	return p
}

func (x ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_game_v1alpha1_game_proto_enumTypes[0].Descriptor()
}

func (ActionType) Type() protoreflect.EnumType {
	return &file_game_v1alpha1_game_proto_enumTypes[0]
}

func (x ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionType.Descriptor instead.
func (ActionType) EnumDescriptor() ([]byte, []int) {
	return file_game_v1alpha1_game_proto_rawDescGZIP(), []int{0}
}

// GameStatus represents the status of the game.
type GameStatus int32

const (
	// GAME_STATUS_UNSPECIFIED is the default unspecified status.
	GameStatus_GAME_STATUS_UNSPECIFIED GameStatus = 0
	// GAME_STATUS_WAITING indicates the game is waiting for players or to start.
	GameStatus_GAME_STATUS_WAITING GameStatus = 1
	// GAME_STATUS_IN_PROGRESS indicates the game is currently being played.
	GameStatus_GAME_STATUS_IN_PROGRESS GameStatus = 2
	// GAME_STATUS_FINISHED indicates the game has ended.
	GameStatus_GAME_STATUS_FINISHED GameStatus = 3
)

// Enum value maps for GameStatus.
var (
	GameStatus_name = map[int32]string{
		0: "GAME_STATUS_UNSPECIFIED",
		1: "GAME_STATUS_WAITING",
		2: "GAME_STATUS_IN_PROGRESS",
		3: "GAME_STATUS_FINISHED",
	}
	GameStatus_value = map[string]int32{
		"GAME_STATUS_UNSPECIFIED": 0,
		"GAME_STATUS_WAITING":     1,
		"GAME_STATUS_IN_PROGRESS": 2,
		"GAME_STATUS_FINISHED":    3,
	}
)

func (x GameStatus) Enum() *GameStatus {
	p := new(GameStatus)
	*p = x
	return p
}

func (x GameStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_game_v1alpha1_game_proto_enumTypes[1].Descriptor()
}

func (GameStatus) Type() protoreflect.EnumType {
	return &file_game_v1alpha1_game_proto_enumTypes[1]
}

func (x GameStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameStatus.Descriptor instead.
func (GameStatus) EnumDescriptor() ([]byte, []int) {
	return file_game_v1alpha1_game_proto_rawDescGZIP(), []int{1}
}

// GameRound represents the betting round in the game.
type GameRound int32

const (
	// GAME_ROUND_UNSPECIFIED is the default unspecified round.
	GameRound_GAME_ROUND_UNSPECIFIED GameRound = 0
	// GAME_ROUND_INIT is the initial state before any betting.
	GameRound_GAME_ROUND_INIT GameRound = 1
	// GAME_ROUND_PRE_FLOP is the pre-flop round.
	GameRound_GAME_ROUND_PRE_FLOP GameRound = 2
	// GAME_ROUND_FLOP is the flop round (3 community cards).
	GameRound_GAME_ROUND_FLOP GameRound = 3
	// GAME_ROUND_TURN is the turn round (4th community card).
	GameRound_GAME_ROUND_TURN GameRound = 4
	// GAME_ROUND_RIVER is the river round (5th community card).
	GameRound_GAME_ROUND_RIVER GameRound = 5
	// GAME_ROUND_SHOWDOWN is the showdown where hands are revealed.
	GameRound_GAME_ROUND_SHOWDOWN GameRound = 6
)

// Enum value maps for GameRound.
var (
	GameRound_name = map[int32]string{
		0: "GAME_ROUND_UNSPECIFIED",
		1: "GAME_ROUND_INIT",
		2: "GAME_ROUND_PRE_FLOP",
		3: "GAME_ROUND_FLOP",
		4: "GAME_ROUND_TURN",
		5: "GAME_ROUND_RIVER",
		6: "GAME_ROUND_SHOWDOWN",
	}
	GameRound_value = map[string]int32{
		"GAME_ROUND_UNSPECIFIED": 0,
		"GAME_ROUND_INIT":        1,
		"GAME_ROUND_PRE_FLOP":    2,
		"GAME_ROUND_FLOP":        3,
		"GAME_ROUND_TURN":        4,
		"GAME_ROUND_RIVER":       5,
		"GAME_ROUND_SHOWDOWN":    6,
	}
)

func (x GameRound) Enum() *GameRound {
	p := new(GameRound)
	*p = x
	return p
}

func (x GameRound) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameRound) Descriptor() protoreflect.EnumDescriptor {
	return file_game_v1alpha1_game_proto_enumTypes[2].Descriptor()
}

func (GameRound) Type() protoreflect.EnumType {
	return &file_game_v1alpha1_game_proto_enumTypes[2]
}

func (x GameRound) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameRound.Descriptor instead.
func (GameRound) EnumDescriptor() ([]byte, []int) {
	return file_game_v1alpha1_game_proto_rawDescGZIP(), []int{2}
}

// CreateGameRequest is the request to create a new game.
type CreateGameRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// request_id is a unique identifier for idempotency.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// player_id is the unique identifier of the creator.
	PlayerId string `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	// initial_chips is the starting chip count for the player.
	InitialChips int64 `protobuf:"varint,3,opt,name=initial_chips,json=initialChips,proto3" json:"initial_chips,omitempty"`
	// min_bet is the big blind amount.
	MinBet        int64 `protobuf:"varint,4,opt,name=min_bet,json=minBet,proto3" json:"min_bet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGameRequest) Reset() {
	*x = CreateGameRequest{}
	mi := &file_game_v1alpha1_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameRequest) ProtoMessage() {}

func (x *CreateGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1alpha1_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameRequest.ProtoReflect.Descriptor instead.
func (*CreateGameRequest) Descriptor() ([]byte, []int) {
	return file_game_v1alpha1_game_proto_rawDescGZIP(), []int{0}
}

func (x *CreateGameRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CreateGameRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *CreateGameRequest) GetInitialChips() int64 {
	if x != nil {
		return x.InitialChips
	}
	return 0
}

func (x *CreateGameRequest) GetMinBet() int64 {
	if x != nil {
		return x.MinBet
	}
	return 0
}

// CreateGameResponse is the response after creating a game.
type CreateGameResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// game_id is the unique identifier of the created game.
	GameId        string `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGameResponse) Reset() {
	*x = CreateGameResponse{}
	mi := &file_game_v1alpha1_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameResponse) ProtoMessage() {}

func (x *CreateGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1alpha1_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameResponse.ProtoReflect.Descriptor instead.
func (*CreateGameResponse) Descriptor() ([]byte, []int) {
	return file_game_v1alpha1_game_proto_rawDescGZIP(), []int{1}
}

func (x *CreateGameResponse) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

// JoinGameRequest is the request to join an existing game.
type JoinGameRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// game_id is the identifier of the game to join.
	GameId string `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	// player_id is the unique identifier of the joining player.
	PlayerId      string `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinGameRequest) Reset() {
	*x = JoinGameRequest{}
	mi := &file_game_v1alpha1_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGameRequest) ProtoMessage() {}

func (x *JoinGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1alpha1_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGameRequest.ProtoReflect.Descriptor instead.
func (*JoinGameRequest) Descriptor() ([]byte, []int) {
	return file_game_v1alpha1_game_proto_rawDescGZIP(), []int{2}
}

func (x *JoinGameRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *JoinGameRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

// JoinGameResponse is the response after joining a game.
type JoinGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinGameResponse) Reset() {
	*x = JoinGameResponse{}
	mi := &file_game_v1alpha1_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGameResponse) ProtoMessage() {}

func (x *JoinGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1alpha1_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGameResponse.ProtoReflect.Descriptor instead.
func (*JoinGameResponse) Descriptor() ([]byte, []int) {
	return file_game_v1alpha1_game_proto_rawDescGZIP(), []int{3}
}

// StartGameRequest is the request to start a game.
type StartGameRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// game_id is the identifier of the game to start.
	GameId string `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	// player_id is the identifier of the player requesting the start (usually the host).
	PlayerId      string `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartGameRequest) Reset() {
	*x = StartGameRequest{}
	mi := &file_game_v1alpha1_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameRequest) ProtoMessage() {}

func (x *StartGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1alpha1_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameRequest.ProtoReflect.Descriptor instead.
func (*StartGameRequest) Descriptor() ([]byte, []int) {
	return file_game_v1alpha1_game_proto_rawDescGZIP(), []int{4}
}

func (x *StartGameRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *StartGameRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

// StartGameResponse is the response after starting a game.
type StartGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartGameResponse) Reset() {
	*x = StartGameResponse{}
	mi := &file_game_v1alpha1_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameResponse) ProtoMessage() {}

func (x *StartGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1alpha1_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameResponse.ProtoReflect.Descriptor instead.
func (*StartGameResponse) Descriptor() ([]byte, []int) {
	return file_game_v1alpha1_game_proto_rawDescGZIP(), []int{5}
}

// PlayActionRequest is the request to perform a game action.
type PlayActionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// request_id is a unique identifier for idempotency.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// game_id is the identifier of the game.
	GameId string `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	// player_id is the identifier of the player performing the action.
	PlayerId string `protobuf:"bytes,3,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	// action_type is the type of action being performed.
	ActionType ActionType `protobuf:"varint,4,opt,name=action_type,json=actionType,proto3,enum=game.v1alpha1.ActionType" json:"action_type,omitempty"`
	// amount is the amount of chips for the action.
	// For RAISE, it typically represents the total amount bet in the current round.
	Amount        int64 `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayActionRequest) Reset() {
	*x = PlayActionRequest{}
	mi := &file_game_v1alpha1_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayActionRequest) ProtoMessage() {}

func (x *PlayActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1alpha1_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayActionRequest.ProtoReflect.Descriptor instead.
func (*PlayActionRequest) Descriptor() ([]byte, []int) {
	return file_game_v1alpha1_game_proto_rawDescGZIP(), []int{6}
}

func (x *PlayActionRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PlayActionRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *PlayActionRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayActionRequest) GetActionType() ActionType {
	if x != nil {
		return x.ActionType
	}
	return ActionType_ACTION_TYPE_UNSPECIFIED
}

func (x *PlayActionRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// PlayActionResponse is the response after performing an action.
type PlayActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayActionResponse) Reset() {
	*x = PlayActionResponse{}
	mi := &file_game_v1alpha1_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayActionResponse) ProtoMessage() {}

func (x *PlayActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1alpha1_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayActionResponse.ProtoReflect.Descriptor instead.
func (*PlayActionResponse) Descriptor() ([]byte, []int) {
	return file_game_v1alpha1_game_proto_rawDescGZIP(), []int{7}
}

// GetGameStateRequest is the request to retrieve current game state.
type GetGameStateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// game_id is the identifier of the game.
	GameId string `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	// player_id is the identifier of the player requesting state.
	PlayerId      string `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameStateRequest) Reset() {
	*x = GetGameStateRequest{}
	mi := &file_game_v1alpha1_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameStateRequest) ProtoMessage() {}

func (x *GetGameStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1alpha1_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameStateRequest.ProtoReflect.Descriptor instead.
func (*GetGameStateRequest) Descriptor() ([]byte, []int) {
	return file_game_v1alpha1_game_proto_rawDescGZIP(), []int{8}
}

func (x *GetGameStateRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GetGameStateRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

// GetGameStateResponse contains the current state of the game.
type GetGameStateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// game_id is the identifier of the game.
	GameId string `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	// status is the current status of the game.
	Status GameStatus `protobuf:"varint,2,opt,name=status,proto3,enum=game.v1alpha1.GameStatus" json:"status,omitempty"`
	// current_round is the current betting round.
	CurrentRound GameRound `protobuf:"varint,3,opt,name=current_round,json=currentRound,proto3,enum=game.v1alpha1.GameRound" json:"current_round,omitempty"`
	// pot is the total chips in the pot.
	Pot int64 `protobuf:"varint,4,opt,name=pot,proto3" json:"pot,omitempty"`
	// min_bet is the current minimum bet required.
	MinBet int64 `protobuf:"varint,5,opt,name=min_bet,json=minBet,proto3" json:"min_bet,omitempty"`
	// community_cards are the public cards on the table.
	CommunityCards []*v1alpha1.Card `protobuf:"bytes,6,rep,name=community_cards,json=communityCards,proto3" json:"community_cards,omitempty"`
	// players is the list of players in the game.
	Players []*PlayerState `protobuf:"bytes,7,rep,name=players,proto3" json:"players,omitempty"`
	// action_pos is the index of the player whose turn it is.
	ActionPos int32 `protobuf:"varint,8,opt,name=action_pos,json=actionPos,proto3" json:"action_pos,omitempty"`
	// betting_closed indicates if the betting for the current round is closed.
	BettingClosed bool `protobuf:"varint,9,opt,name=betting_closed,json=bettingClosed,proto3" json:"betting_closed,omitempty"`
	// highest_wager is the highest bet in the current round.
	HighestWager int64 `protobuf:"varint,10,opt,name=highest_wager,json=highestWager,proto3" json:"highest_wager,omitempty"`
	// action_deadline is the timestamp when the current turn will expire.
	ActionDeadline *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=action_deadline,json=actionDeadline,proto3" json:"action_deadline,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetGameStateResponse) Reset() {
	*x = GetGameStateResponse{}
	mi := &file_game_v1alpha1_game_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameStateResponse) ProtoMessage() {}

func (x *GetGameStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1alpha1_game_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameStateResponse.ProtoReflect.Descriptor instead.
func (*GetGameStateResponse) Descriptor() ([]byte, []int) {
	return file_game_v1alpha1_game_proto_rawDescGZIP(), []int{9}
}

func (x *GetGameStateResponse) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GetGameStateResponse) GetStatus() GameStatus {
	if x != nil {
		return x.Status
	}
	return GameStatus_GAME_STATUS_UNSPECIFIED
}

func (x *GetGameStateResponse) GetCurrentRound() GameRound {
	if x != nil {
		return x.CurrentRound
	}
	return GameRound_GAME_ROUND_UNSPECIFIED
}

func (x *GetGameStateResponse) GetPot() int64 {
	if x != nil {
		return x.Pot
	}
	return 0
}

func (x *GetGameStateResponse) GetMinBet() int64 {
	if x != nil {
		return x.MinBet
	}
	return 0
}

func (x *GetGameStateResponse) GetCommunityCards() []*v1alpha1.Card {
	if x != nil {
		return x.CommunityCards
	}
	return nil
}

func (x *GetGameStateResponse) GetPlayers() []*PlayerState {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *GetGameStateResponse) GetActionPos() int32 {
	if x != nil {
		return x.ActionPos
	}
	return 0
}

func (x *GetGameStateResponse) GetBettingClosed() bool {
	if x != nil {
		return x.BettingClosed
	}
	return false
}

func (x *GetGameStateResponse) GetHighestWager() int64 {
	if x != nil {
		return x.HighestWager
	}
	return 0
}

func (x *GetGameStateResponse) GetActionDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.ActionDeadline
	}
	return nil
}

// WatchGameRequest is the request to subscribe to game updates.
type WatchGameRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// game_id is the identifier of the game to watch.
	GameId string `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	// player_id is the identifier of the player watching.
	PlayerId      string `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchGameRequest) Reset() {
	*x = WatchGameRequest{}
	mi := &file_game_v1alpha1_game_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchGameRequest) ProtoMessage() {}

func (x *WatchGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1alpha1_game_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchGameRequest.ProtoReflect.Descriptor instead.
func (*WatchGameRequest) Descriptor() ([]byte, []int) {
	return file_game_v1alpha1_game_proto_rawDescGZIP(), []int{10}
}

func (x *WatchGameRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *WatchGameRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

// WatchGameResponse is a stream of game state updates.
type WatchGameResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// state is the payload containing the current game state.
	State         *GetGameStateResponse `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchGameResponse) Reset() {
	*x = WatchGameResponse{}
	mi := &file_game_v1alpha1_game_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchGameResponse) ProtoMessage() {}

func (x *WatchGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1alpha1_game_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchGameResponse.ProtoReflect.Descriptor instead.
func (*WatchGameResponse) Descriptor() ([]byte, []int) {
	return file_game_v1alpha1_game_proto_rawDescGZIP(), []int{11}
}

func (x *WatchGameResponse) GetState() *GetGameStateResponse {
	if x != nil {
		return x.State
	}
	return nil
}

// PlayerState represents the state of a single player in the game.
type PlayerState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the unique identifier of the player.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// chips is the current chip count of the player.
	Chips int64 `protobuf:"varint,2,opt,name=chips,proto3" json:"chips,omitempty"`
	// round_bet is the amount the player has bet in the current round.
	RoundBet int64 `protobuf:"varint,3,opt,name=round_bet,json=roundBet,proto3" json:"round_bet,omitempty"`
	// folded indicates if the player has folded.
	Folded bool `protobuf:"varint,4,opt,name=folded,proto3" json:"folded,omitempty"`
	// hole_cards are populated only during Showdown or when the player is viewing their own hand.
	HoleCards []*v1alpha1.Card `protobuf:"bytes,5,rep,name=hole_cards,json=holeCards,proto3" json:"hole_cards,omitempty"`
	// is_turn indicates if it is currently this player's turn.
	IsTurn        bool `protobuf:"varint,6,opt,name=is_turn,json=isTurn,proto3" json:"is_turn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerState) Reset() {
	*x = PlayerState{}
	mi := &file_game_v1alpha1_game_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerState) ProtoMessage() {}

func (x *PlayerState) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1alpha1_game_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerState.ProtoReflect.Descriptor instead.
func (*PlayerState) Descriptor() ([]byte, []int) {
	return file_game_v1alpha1_game_proto_rawDescGZIP(), []int{12}
}

func (x *PlayerState) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PlayerState) GetChips() int64 {
	if x != nil {
		return x.Chips
	}
	return 0
}

func (x *PlayerState) GetRoundBet() int64 {
	if x != nil {
		return x.RoundBet
	}
	return 0
}

func (x *PlayerState) GetFolded() bool {
	if x != nil {
		return x.Folded
	}
	return false
}

func (x *PlayerState) GetHoleCards() []*v1alpha1.Card {
	if x != nil {
		return x.HoleCards
	}
	return nil
}

func (x *PlayerState) GetIsTurn() bool {
	if x != nil {
		return x.IsTurn
	}
	return false
}

// KickPlayerRequest is the request to kick a player from the game.
type KickPlayerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the game
	GameId string `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	// The ID of the player to be kicked (can be a bot ID, e.g., "BOT_1")
	PlayerId string `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	// The ID of the player performing the kick (must be the Host)
	KickerId      string `protobuf:"bytes,3,opt,name=kicker_id,json=kickerId,proto3" json:"kicker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickPlayerRequest) Reset() {
	*x = KickPlayerRequest{}
	mi := &file_game_v1alpha1_game_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickPlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickPlayerRequest) ProtoMessage() {}

func (x *KickPlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1alpha1_game_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickPlayerRequest.ProtoReflect.Descriptor instead.
func (*KickPlayerRequest) Descriptor() ([]byte, []int) {
	return file_game_v1alpha1_game_proto_rawDescGZIP(), []int{13}
}

func (x *KickPlayerRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *KickPlayerRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *KickPlayerRequest) GetKickerId() string {
	if x != nil {
		return x.KickerId
	}
	return ""
}

// KickPlayerResponse is the response after kicking a player.
type KickPlayerResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Returns the updated game state immediately after kicking
	// This is optional, but helpful for the client to update UI instantly
	State         *GetGameStateResponse `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickPlayerResponse) Reset() {
	*x = KickPlayerResponse{}
	mi := &file_game_v1alpha1_game_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickPlayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickPlayerResponse) ProtoMessage() {}

func (x *KickPlayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1alpha1_game_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickPlayerResponse.ProtoReflect.Descriptor instead.
func (*KickPlayerResponse) Descriptor() ([]byte, []int) {
	return file_game_v1alpha1_game_proto_rawDescGZIP(), []int{14}
}

func (x *KickPlayerResponse) GetState() *GetGameStateResponse {
	if x != nil {
		return x.State
	}
	return nil
}

var File_game_v1alpha1_game_proto protoreflect.FileDescriptor

const file_game_v1alpha1_game_proto_rawDesc = "" +
	"\n" +
	"\x18game/v1alpha1/game.proto\x12\rgame.v1alpha1\x1a\x18card/v1alpha1/card.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8d\x01\n" +
	"\x11CreateGameRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12#\n" +
	"\rinitial_chips\x18\x03 \x01(\x03R\finitialChips\x12\x17\n" +
	"\amin_bet\x18\x04 \x01(\x03R\x06minBet\"-\n" +
	"\x12CreateGameResponse\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\"G\n" +
	"\x0fJoinGameRequest\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\"\x12\n" +
	"\x10JoinGameResponse\"H\n" +
	"\x10StartGameRequest\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\"\x13\n" +
	"\x11StartGameResponse\"\xbc\x01\n" +
	"\x11PlayActionRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\x12\x1b\n" +
	"\tplayer_id\x18\x03 \x01(\tR\bplayerId\x12:\n" +
	"\vaction_type\x18\x04 \x01(\x0e2\x19.game.v1alpha1.ActionTypeR\n" +
	"actionType\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\"\x14\n" +
	"\x12PlayActionResponse\"K\n" +
	"\x13GetGameStateRequest\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\"\xf0\x03\n" +
	"\x14GetGameStateResponse\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x121\n" +
	"\x06status\x18\x02 \x01(\x0e2\x19.game.v1alpha1.GameStatusR\x06status\x12=\n" +
	"\rcurrent_round\x18\x03 \x01(\x0e2\x18.game.v1alpha1.GameRoundR\fcurrentRound\x12\x10\n" +
	"\x03pot\x18\x04 \x01(\x03R\x03pot\x12\x17\n" +
	"\amin_bet\x18\x05 \x01(\x03R\x06minBet\x12<\n" +
	"\x0fcommunity_cards\x18\x06 \x03(\v2\x13.card.v1alpha1.CardR\x0ecommunityCards\x124\n" +
	"\aplayers\x18\a \x03(\v2\x1a.game.v1alpha1.PlayerStateR\aplayers\x12\x1d\n" +
	"\n" +
	"action_pos\x18\b \x01(\x05R\tactionPos\x12%\n" +
	"\x0ebetting_closed\x18\t \x01(\bR\rbettingClosed\x12#\n" +
	"\rhighest_wager\x18\n" +
	" \x01(\x03R\fhighestWager\x12C\n" +
	"\x0faction_deadline\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\x0eactionDeadline\"H\n" +
	"\x10WatchGameRequest\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\"N\n" +
	"\x11WatchGameResponse\x129\n" +
	"\x05state\x18\x01 \x01(\v2#.game.v1alpha1.GetGameStateResponseR\x05state\"\xb5\x01\n" +
	"\vPlayerState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05chips\x18\x02 \x01(\x03R\x05chips\x12\x1b\n" +
	"\tround_bet\x18\x03 \x01(\x03R\broundBet\x12\x16\n" +
	"\x06folded\x18\x04 \x01(\bR\x06folded\x122\n" +
	"\n" +
	"hole_cards\x18\x05 \x03(\v2\x13.card.v1alpha1.CardR\tholeCards\x12\x17\n" +
	"\ais_turn\x18\x06 \x01(\bR\x06isTurn\"f\n" +
	"\x11KickPlayerRequest\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12\x1b\n" +
	"\tkicker_id\x18\x03 \x01(\tR\bkickerId\"O\n" +
	"\x12KickPlayerResponse\x129\n" +
	"\x05state\x18\x01 \x01(\v2#.game.v1alpha1.GetGameStateResponseR\x05state*\x9b\x01\n" +
	"\n" +
	"ActionType\x12\x1b\n" +
	"\x17ACTION_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ACTION_TYPE_FOLD\x10\x01\x12\x15\n" +
	"\x11ACTION_TYPE_CHECK\x10\x02\x12\x14\n" +
	"\x10ACTION_TYPE_CALL\x10\x03\x12\x15\n" +
	"\x11ACTION_TYPE_RAISE\x10\x04\x12\x16\n" +
	"\x12ACTION_TYPE_ALL_IN\x10\x05*y\n" +
	"\n" +
	"GameStatus\x12\x1b\n" +
	"\x17GAME_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13GAME_STATUS_WAITING\x10\x01\x12\x1b\n" +
	"\x17GAME_STATUS_IN_PROGRESS\x10\x02\x12\x18\n" +
	"\x14GAME_STATUS_FINISHED\x10\x03*\xae\x01\n" +
	"\tGameRound\x12\x1a\n" +
	"\x16GAME_ROUND_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fGAME_ROUND_INIT\x10\x01\x12\x17\n" +
	"\x13GAME_ROUND_PRE_FLOP\x10\x02\x12\x13\n" +
	"\x0fGAME_ROUND_FLOP\x10\x03\x12\x13\n" +
	"\x0fGAME_ROUND_TURN\x10\x04\x12\x14\n" +
	"\x10GAME_ROUND_RIVER\x10\x05\x12\x17\n" +
	"\x13GAME_ROUND_SHOWDOWN\x10\x062\xce\x04\n" +
	"\vGameService\x12Q\n" +
	"\n" +
	"CreateGame\x12 .game.v1alpha1.CreateGameRequest\x1a!.game.v1alpha1.CreateGameResponse\x12K\n" +
	"\bJoinGame\x12\x1e.game.v1alpha1.JoinGameRequest\x1a\x1f.game.v1alpha1.JoinGameResponse\x12N\n" +
	"\tStartGame\x12\x1f.game.v1alpha1.StartGameRequest\x1a .game.v1alpha1.StartGameResponse\x12Q\n" +
	"\n" +
	"PlayAction\x12 .game.v1alpha1.PlayActionRequest\x1a!.game.v1alpha1.PlayActionResponse\x12W\n" +
	"\fGetGameState\x12\".game.v1alpha1.GetGameStateRequest\x1a#.game.v1alpha1.GetGameStateResponse\x12P\n" +
	"\tWatchGame\x12\x1f.game.v1alpha1.WatchGameRequest\x1a .game.v1alpha1.WatchGameResponse0\x01\x12Q\n" +
	"\n" +
	"KickPlayer\x12 .game.v1alpha1.KickPlayerRequest\x1a!.game.v1alpha1.KickPlayerResponseB5Z3github.com/openpoker-dev/gengo/game/v1alpha1;gamepbb\x06proto3"

var (
	file_game_v1alpha1_game_proto_rawDescOnce sync.Once
	file_game_v1alpha1_game_proto_rawDescData []byte
)

func file_game_v1alpha1_game_proto_rawDescGZIP() []byte {
	file_game_v1alpha1_game_proto_rawDescOnce.Do(func() {
		file_game_v1alpha1_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_v1alpha1_game_proto_rawDesc), len(file_game_v1alpha1_game_proto_rawDesc)))
	})
	return file_game_v1alpha1_game_proto_rawDescData
}

var file_game_v1alpha1_game_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_game_v1alpha1_game_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_game_v1alpha1_game_proto_goTypes = []any{
	(ActionType)(0),               // 0: game.v1alpha1.ActionType
	(GameStatus)(0),               // 1: game.v1alpha1.GameStatus
	(GameRound)(0),                // 2: game.v1alpha1.GameRound
	(*CreateGameRequest)(nil),     // 3: game.v1alpha1.CreateGameRequest
	(*CreateGameResponse)(nil),    // 4: game.v1alpha1.CreateGameResponse
	(*JoinGameRequest)(nil),       // 5: game.v1alpha1.JoinGameRequest
	(*JoinGameResponse)(nil),      // 6: game.v1alpha1.JoinGameResponse
	(*StartGameRequest)(nil),      // 7: game.v1alpha1.StartGameRequest
	(*StartGameResponse)(nil),     // 8: game.v1alpha1.StartGameResponse
	(*PlayActionRequest)(nil),     // 9: game.v1alpha1.PlayActionRequest
	(*PlayActionResponse)(nil),    // 10: game.v1alpha1.PlayActionResponse
	(*GetGameStateRequest)(nil),   // 11: game.v1alpha1.GetGameStateRequest
	(*GetGameStateResponse)(nil),  // 12: game.v1alpha1.GetGameStateResponse
	(*WatchGameRequest)(nil),      // 13: game.v1alpha1.WatchGameRequest
	(*WatchGameResponse)(nil),     // 14: game.v1alpha1.WatchGameResponse
	(*PlayerState)(nil),           // 15: game.v1alpha1.PlayerState
	(*KickPlayerRequest)(nil),     // 16: game.v1alpha1.KickPlayerRequest
	(*KickPlayerResponse)(nil),    // 17: game.v1alpha1.KickPlayerResponse
	(*v1alpha1.Card)(nil),         // 18: card.v1alpha1.Card
	(*timestamppb.Timestamp)(nil), // 19: google.protobuf.Timestamp
}
var file_game_v1alpha1_game_proto_depIdxs = []int32{
	0,  // 0: game.v1alpha1.PlayActionRequest.action_type:type_name -> game.v1alpha1.ActionType
	1,  // 1: game.v1alpha1.GetGameStateResponse.status:type_name -> game.v1alpha1.GameStatus
	2,  // 2: game.v1alpha1.GetGameStateResponse.current_round:type_name -> game.v1alpha1.GameRound
	18, // 3: game.v1alpha1.GetGameStateResponse.community_cards:type_name -> card.v1alpha1.Card
	15, // 4: game.v1alpha1.GetGameStateResponse.players:type_name -> game.v1alpha1.PlayerState
	19, // 5: game.v1alpha1.GetGameStateResponse.action_deadline:type_name -> google.protobuf.Timestamp
	12, // 6: game.v1alpha1.WatchGameResponse.state:type_name -> game.v1alpha1.GetGameStateResponse
	18, // 7: game.v1alpha1.PlayerState.hole_cards:type_name -> card.v1alpha1.Card
	12, // 8: game.v1alpha1.KickPlayerResponse.state:type_name -> game.v1alpha1.GetGameStateResponse
	3,  // 9: game.v1alpha1.GameService.CreateGame:input_type -> game.v1alpha1.CreateGameRequest
	5,  // 10: game.v1alpha1.GameService.JoinGame:input_type -> game.v1alpha1.JoinGameRequest
	7,  // 11: game.v1alpha1.GameService.StartGame:input_type -> game.v1alpha1.StartGameRequest
	9,  // 12: game.v1alpha1.GameService.PlayAction:input_type -> game.v1alpha1.PlayActionRequest
	11, // 13: game.v1alpha1.GameService.GetGameState:input_type -> game.v1alpha1.GetGameStateRequest
	13, // 14: game.v1alpha1.GameService.WatchGame:input_type -> game.v1alpha1.WatchGameRequest
	16, // 15: game.v1alpha1.GameService.KickPlayer:input_type -> game.v1alpha1.KickPlayerRequest
	4,  // 16: game.v1alpha1.GameService.CreateGame:output_type -> game.v1alpha1.CreateGameResponse
	6,  // 17: game.v1alpha1.GameService.JoinGame:output_type -> game.v1alpha1.JoinGameResponse
	8,  // 18: game.v1alpha1.GameService.StartGame:output_type -> game.v1alpha1.StartGameResponse
	10, // 19: game.v1alpha1.GameService.PlayAction:output_type -> game.v1alpha1.PlayActionResponse
	12, // 20: game.v1alpha1.GameService.GetGameState:output_type -> game.v1alpha1.GetGameStateResponse
	14, // 21: game.v1alpha1.GameService.WatchGame:output_type -> game.v1alpha1.WatchGameResponse
	17, // 22: game.v1alpha1.GameService.KickPlayer:output_type -> game.v1alpha1.KickPlayerResponse
	16, // [16:23] is the sub-list for method output_type
	9,  // [9:16] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_game_v1alpha1_game_proto_init() }
func file_game_v1alpha1_game_proto_init() {
	if File_game_v1alpha1_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_v1alpha1_game_proto_rawDesc), len(file_game_v1alpha1_game_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_game_v1alpha1_game_proto_goTypes,
		DependencyIndexes: file_game_v1alpha1_game_proto_depIdxs,
		EnumInfos:         file_game_v1alpha1_game_proto_enumTypes,
		MessageInfos:      file_game_v1alpha1_game_proto_msgTypes,
	}.Build()
	File_game_v1alpha1_game_proto = out.File
	file_game_v1alpha1_game_proto_goTypes = nil
	file_game_v1alpha1_game_proto_depIdxs = nil
}
