// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: game/v1alpha1/game.proto

package gamepbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1alpha1 "github.com/openpoker-dev/gengo/game/v1alpha1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// GameServiceName is the fully-qualified name of the GameService service.
	GameServiceName = "game.v1alpha1.GameService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// GameServiceCreateGameProcedure is the fully-qualified name of the GameService's CreateGame RPC.
	GameServiceCreateGameProcedure = "/game.v1alpha1.GameService/CreateGame"
	// GameServiceJoinGameProcedure is the fully-qualified name of the GameService's JoinGame RPC.
	GameServiceJoinGameProcedure = "/game.v1alpha1.GameService/JoinGame"
	// GameServiceStartGameProcedure is the fully-qualified name of the GameService's StartGame RPC.
	GameServiceStartGameProcedure = "/game.v1alpha1.GameService/StartGame"
	// GameServicePlayActionProcedure is the fully-qualified name of the GameService's PlayAction RPC.
	GameServicePlayActionProcedure = "/game.v1alpha1.GameService/PlayAction"
	// GameServiceGetGameStateProcedure is the fully-qualified name of the GameService's GetGameState
	// RPC.
	GameServiceGetGameStateProcedure = "/game.v1alpha1.GameService/GetGameState"
	// GameServiceWatchGameProcedure is the fully-qualified name of the GameService's WatchGame RPC.
	GameServiceWatchGameProcedure = "/game.v1alpha1.GameService/WatchGame"
)

// GameServiceClient is a client for the game.v1alpha1.GameService service.
type GameServiceClient interface {
	// CreateGame creates a new game room.
	CreateGame(context.Context, *v1alpha1.CreateGameRequest) (*v1alpha1.CreateGameResponse, error)
	// JoinGame joins an existing game room.
	JoinGame(context.Context, *v1alpha1.JoinGameRequest) (*v1alpha1.JoinGameResponse, error)
	// StartGame starts the game (usually restricted to the host).
	StartGame(context.Context, *v1alpha1.StartGameRequest) (*v1alpha1.StartGameResponse, error)
	// PlayAction performs a player action (Fold, Check, Call, Raise).
	PlayAction(context.Context, *v1alpha1.PlayActionRequest) (*v1alpha1.PlayActionResponse, error)
	// GetGameState retrieves the current game state (used for polling or reconnection).
	GetGameState(context.Context, *v1alpha1.GetGameStateRequest) (*v1alpha1.GetGameStateResponse, error)
	// WatchGame streams game updates to the client in real-time.
	WatchGame(context.Context, *v1alpha1.WatchGameRequest) (*connect.ServerStreamForClient[v1alpha1.WatchGameResponse], error)
}

// NewGameServiceClient constructs a client for the game.v1alpha1.GameService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewGameServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) GameServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	gameServiceMethods := v1alpha1.File_game_v1alpha1_game_proto.Services().ByName("GameService").Methods()
	return &gameServiceClient{
		createGame: connect.NewClient[v1alpha1.CreateGameRequest, v1alpha1.CreateGameResponse](
			httpClient,
			baseURL+GameServiceCreateGameProcedure,
			connect.WithSchema(gameServiceMethods.ByName("CreateGame")),
			connect.WithClientOptions(opts...),
		),
		joinGame: connect.NewClient[v1alpha1.JoinGameRequest, v1alpha1.JoinGameResponse](
			httpClient,
			baseURL+GameServiceJoinGameProcedure,
			connect.WithSchema(gameServiceMethods.ByName("JoinGame")),
			connect.WithClientOptions(opts...),
		),
		startGame: connect.NewClient[v1alpha1.StartGameRequest, v1alpha1.StartGameResponse](
			httpClient,
			baseURL+GameServiceStartGameProcedure,
			connect.WithSchema(gameServiceMethods.ByName("StartGame")),
			connect.WithClientOptions(opts...),
		),
		playAction: connect.NewClient[v1alpha1.PlayActionRequest, v1alpha1.PlayActionResponse](
			httpClient,
			baseURL+GameServicePlayActionProcedure,
			connect.WithSchema(gameServiceMethods.ByName("PlayAction")),
			connect.WithClientOptions(opts...),
		),
		getGameState: connect.NewClient[v1alpha1.GetGameStateRequest, v1alpha1.GetGameStateResponse](
			httpClient,
			baseURL+GameServiceGetGameStateProcedure,
			connect.WithSchema(gameServiceMethods.ByName("GetGameState")),
			connect.WithClientOptions(opts...),
		),
		watchGame: connect.NewClient[v1alpha1.WatchGameRequest, v1alpha1.WatchGameResponse](
			httpClient,
			baseURL+GameServiceWatchGameProcedure,
			connect.WithSchema(gameServiceMethods.ByName("WatchGame")),
			connect.WithClientOptions(opts...),
		),
	}
}

// gameServiceClient implements GameServiceClient.
type gameServiceClient struct {
	createGame   *connect.Client[v1alpha1.CreateGameRequest, v1alpha1.CreateGameResponse]
	joinGame     *connect.Client[v1alpha1.JoinGameRequest, v1alpha1.JoinGameResponse]
	startGame    *connect.Client[v1alpha1.StartGameRequest, v1alpha1.StartGameResponse]
	playAction   *connect.Client[v1alpha1.PlayActionRequest, v1alpha1.PlayActionResponse]
	getGameState *connect.Client[v1alpha1.GetGameStateRequest, v1alpha1.GetGameStateResponse]
	watchGame    *connect.Client[v1alpha1.WatchGameRequest, v1alpha1.WatchGameResponse]
}

// CreateGame calls game.v1alpha1.GameService.CreateGame.
func (c *gameServiceClient) CreateGame(ctx context.Context, req *v1alpha1.CreateGameRequest) (*v1alpha1.CreateGameResponse, error) {
	response, err := c.createGame.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// JoinGame calls game.v1alpha1.GameService.JoinGame.
func (c *gameServiceClient) JoinGame(ctx context.Context, req *v1alpha1.JoinGameRequest) (*v1alpha1.JoinGameResponse, error) {
	response, err := c.joinGame.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// StartGame calls game.v1alpha1.GameService.StartGame.
func (c *gameServiceClient) StartGame(ctx context.Context, req *v1alpha1.StartGameRequest) (*v1alpha1.StartGameResponse, error) {
	response, err := c.startGame.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// PlayAction calls game.v1alpha1.GameService.PlayAction.
func (c *gameServiceClient) PlayAction(ctx context.Context, req *v1alpha1.PlayActionRequest) (*v1alpha1.PlayActionResponse, error) {
	response, err := c.playAction.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// GetGameState calls game.v1alpha1.GameService.GetGameState.
func (c *gameServiceClient) GetGameState(ctx context.Context, req *v1alpha1.GetGameStateRequest) (*v1alpha1.GetGameStateResponse, error) {
	response, err := c.getGameState.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// WatchGame calls game.v1alpha1.GameService.WatchGame.
func (c *gameServiceClient) WatchGame(ctx context.Context, req *v1alpha1.WatchGameRequest) (*connect.ServerStreamForClient[v1alpha1.WatchGameResponse], error) {
	return c.watchGame.CallServerStream(ctx, connect.NewRequest(req))
}

// GameServiceHandler is an implementation of the game.v1alpha1.GameService service.
type GameServiceHandler interface {
	// CreateGame creates a new game room.
	CreateGame(context.Context, *v1alpha1.CreateGameRequest) (*v1alpha1.CreateGameResponse, error)
	// JoinGame joins an existing game room.
	JoinGame(context.Context, *v1alpha1.JoinGameRequest) (*v1alpha1.JoinGameResponse, error)
	// StartGame starts the game (usually restricted to the host).
	StartGame(context.Context, *v1alpha1.StartGameRequest) (*v1alpha1.StartGameResponse, error)
	// PlayAction performs a player action (Fold, Check, Call, Raise).
	PlayAction(context.Context, *v1alpha1.PlayActionRequest) (*v1alpha1.PlayActionResponse, error)
	// GetGameState retrieves the current game state (used for polling or reconnection).
	GetGameState(context.Context, *v1alpha1.GetGameStateRequest) (*v1alpha1.GetGameStateResponse, error)
	// WatchGame streams game updates to the client in real-time.
	WatchGame(context.Context, *v1alpha1.WatchGameRequest, *connect.ServerStream[v1alpha1.WatchGameResponse]) error
}

// NewGameServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewGameServiceHandler(svc GameServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	gameServiceMethods := v1alpha1.File_game_v1alpha1_game_proto.Services().ByName("GameService").Methods()
	gameServiceCreateGameHandler := connect.NewUnaryHandlerSimple(
		GameServiceCreateGameProcedure,
		svc.CreateGame,
		connect.WithSchema(gameServiceMethods.ByName("CreateGame")),
		connect.WithHandlerOptions(opts...),
	)
	gameServiceJoinGameHandler := connect.NewUnaryHandlerSimple(
		GameServiceJoinGameProcedure,
		svc.JoinGame,
		connect.WithSchema(gameServiceMethods.ByName("JoinGame")),
		connect.WithHandlerOptions(opts...),
	)
	gameServiceStartGameHandler := connect.NewUnaryHandlerSimple(
		GameServiceStartGameProcedure,
		svc.StartGame,
		connect.WithSchema(gameServiceMethods.ByName("StartGame")),
		connect.WithHandlerOptions(opts...),
	)
	gameServicePlayActionHandler := connect.NewUnaryHandlerSimple(
		GameServicePlayActionProcedure,
		svc.PlayAction,
		connect.WithSchema(gameServiceMethods.ByName("PlayAction")),
		connect.WithHandlerOptions(opts...),
	)
	gameServiceGetGameStateHandler := connect.NewUnaryHandlerSimple(
		GameServiceGetGameStateProcedure,
		svc.GetGameState,
		connect.WithSchema(gameServiceMethods.ByName("GetGameState")),
		connect.WithHandlerOptions(opts...),
	)
	gameServiceWatchGameHandler := connect.NewServerStreamHandlerSimple(
		GameServiceWatchGameProcedure,
		svc.WatchGame,
		connect.WithSchema(gameServiceMethods.ByName("WatchGame")),
		connect.WithHandlerOptions(opts...),
	)
	return "/game.v1alpha1.GameService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case GameServiceCreateGameProcedure:
			gameServiceCreateGameHandler.ServeHTTP(w, r)
		case GameServiceJoinGameProcedure:
			gameServiceJoinGameHandler.ServeHTTP(w, r)
		case GameServiceStartGameProcedure:
			gameServiceStartGameHandler.ServeHTTP(w, r)
		case GameServicePlayActionProcedure:
			gameServicePlayActionHandler.ServeHTTP(w, r)
		case GameServiceGetGameStateProcedure:
			gameServiceGetGameStateHandler.ServeHTTP(w, r)
		case GameServiceWatchGameProcedure:
			gameServiceWatchGameHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedGameServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedGameServiceHandler struct{}

func (UnimplementedGameServiceHandler) CreateGame(context.Context, *v1alpha1.CreateGameRequest) (*v1alpha1.CreateGameResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("game.v1alpha1.GameService.CreateGame is not implemented"))
}

func (UnimplementedGameServiceHandler) JoinGame(context.Context, *v1alpha1.JoinGameRequest) (*v1alpha1.JoinGameResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("game.v1alpha1.GameService.JoinGame is not implemented"))
}

func (UnimplementedGameServiceHandler) StartGame(context.Context, *v1alpha1.StartGameRequest) (*v1alpha1.StartGameResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("game.v1alpha1.GameService.StartGame is not implemented"))
}

func (UnimplementedGameServiceHandler) PlayAction(context.Context, *v1alpha1.PlayActionRequest) (*v1alpha1.PlayActionResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("game.v1alpha1.GameService.PlayAction is not implemented"))
}

func (UnimplementedGameServiceHandler) GetGameState(context.Context, *v1alpha1.GetGameStateRequest) (*v1alpha1.GetGameStateResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("game.v1alpha1.GameService.GetGameState is not implemented"))
}

func (UnimplementedGameServiceHandler) WatchGame(context.Context, *v1alpha1.WatchGameRequest, *connect.ServerStream[v1alpha1.WatchGameResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("game.v1alpha1.GameService.WatchGame is not implemented"))
}
