// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: card/v1alpha1/card_api.proto

package cardconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1alpha1 "github.com/openpoker-dev/gengo/card/v1alpha1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// CardServiceName is the fully-qualified name of the CardService service.
	CardServiceName = "card.v1alpha1.CardService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// CardServiceDealProcedure is the fully-qualified name of the CardService's Deal RPC.
	CardServiceDealProcedure = "/card.v1alpha1.CardService/Deal"
	// CardServicePingProcedure is the fully-qualified name of the CardService's Ping RPC.
	CardServicePingProcedure = "/card.v1alpha1.CardService/Ping"
)

// CardServiceClient is a client for the card.v1alpha1.CardService service.
type CardServiceClient interface {
	// Deal
	Deal(context.Context, *v1alpha1.DealRequest) (*v1alpha1.DealResponse, error)
	// Ping heartbeat
	Ping(context.Context, *v1alpha1.PingRequest) (*v1alpha1.PingResponse, error)
}

// NewCardServiceClient constructs a client for the card.v1alpha1.CardService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewCardServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) CardServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	cardServiceMethods := v1alpha1.File_card_v1alpha1_card_api_proto.Services().ByName("CardService").Methods()
	return &cardServiceClient{
		deal: connect.NewClient[v1alpha1.DealRequest, v1alpha1.DealResponse](
			httpClient,
			baseURL+CardServiceDealProcedure,
			connect.WithSchema(cardServiceMethods.ByName("Deal")),
			connect.WithClientOptions(opts...),
		),
		ping: connect.NewClient[v1alpha1.PingRequest, v1alpha1.PingResponse](
			httpClient,
			baseURL+CardServicePingProcedure,
			connect.WithSchema(cardServiceMethods.ByName("Ping")),
			connect.WithClientOptions(opts...),
		),
	}
}

// cardServiceClient implements CardServiceClient.
type cardServiceClient struct {
	deal *connect.Client[v1alpha1.DealRequest, v1alpha1.DealResponse]
	ping *connect.Client[v1alpha1.PingRequest, v1alpha1.PingResponse]
}

// Deal calls card.v1alpha1.CardService.Deal.
func (c *cardServiceClient) Deal(ctx context.Context, req *v1alpha1.DealRequest) (*v1alpha1.DealResponse, error) {
	response, err := c.deal.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// Ping calls card.v1alpha1.CardService.Ping.
func (c *cardServiceClient) Ping(ctx context.Context, req *v1alpha1.PingRequest) (*v1alpha1.PingResponse, error) {
	response, err := c.ping.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// CardServiceHandler is an implementation of the card.v1alpha1.CardService service.
type CardServiceHandler interface {
	// Deal
	Deal(context.Context, *v1alpha1.DealRequest) (*v1alpha1.DealResponse, error)
	// Ping heartbeat
	Ping(context.Context, *v1alpha1.PingRequest) (*v1alpha1.PingResponse, error)
}

// NewCardServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewCardServiceHandler(svc CardServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	cardServiceMethods := v1alpha1.File_card_v1alpha1_card_api_proto.Services().ByName("CardService").Methods()
	cardServiceDealHandler := connect.NewUnaryHandlerSimple(
		CardServiceDealProcedure,
		svc.Deal,
		connect.WithSchema(cardServiceMethods.ByName("Deal")),
		connect.WithHandlerOptions(opts...),
	)
	cardServicePingHandler := connect.NewUnaryHandlerSimple(
		CardServicePingProcedure,
		svc.Ping,
		connect.WithSchema(cardServiceMethods.ByName("Ping")),
		connect.WithHandlerOptions(opts...),
	)
	return "/card.v1alpha1.CardService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case CardServiceDealProcedure:
			cardServiceDealHandler.ServeHTTP(w, r)
		case CardServicePingProcedure:
			cardServicePingHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedCardServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedCardServiceHandler struct{}

func (UnimplementedCardServiceHandler) Deal(context.Context, *v1alpha1.DealRequest) (*v1alpha1.DealResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("card.v1alpha1.CardService.Deal is not implemented"))
}

func (UnimplementedCardServiceHandler) Ping(context.Context, *v1alpha1.PingRequest) (*v1alpha1.PingResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("card.v1alpha1.CardService.Ping is not implemented"))
}
